### ISSUE TITLE
How to detect when the file picker is canceled?

### ISSUE THREAD

**Issue by f957-cua** [Jaaneek/useFilePicker#88]
Hi there!
Brilliant package with many options.

It would be nice to have an onCancel callback to control this stage properly.

I mean to control the cancel button and the picker window close button.

Approach to openning filePicker simultaneously with backdrop behind is very popular nowadays.
And how to cover the case closing backdrop if user close filePicker with any selected files.

I have found the same needs with another library: 
https://github.com/pnp/sp-dev-fx-controls-react/issues/665

**Comment by MrKampla** [comment]
Hi @f957-cua,
I'm afraid I don't have a good answer to your question. Some time ago we wanted to change the open file picker function to return a promise, but it turned out there's no way of implementing rejection reliably across different browsers when user cancels the file selection. Blur and focus events are not fired correctly in browsers, so a user has to make some sort of an action like a click, to focus back the window. 
You can find more details here:
https://github.com/Jaaneek/useFilePicker/pull/58#issuecomment-1496680066

If you want to add a backdrop, I'd probably try to make a workaround by adding a visual element that clearly indicates user has to click on it in order to dismiss. For example a button with an unambiguous icon in the middle of the screen.

**Comment by f957-cua** [comment]
Hi @MrKampla,
Thanks for your quick answer.
Close backdrop is not a bid deal, you can just click on it.
But I want to avoid this click and receive info from package, what file picker window was closed.

Is it possible?

**Comment by MrKampla** [comment]
I understand, but as I said, there's no reliable way of doing that, so use-file-picker package is also not offering such functionality.

**Comment by f957-cua** [comment]
I know.
You're maintaining a nice product, from my POV.
It's only wish for the future.)
Don't give up on this idea, maybe in the future something will have been changed in browsers with event handling.

**Comment by Jaaneek** [comment]
As @MrKampla said:

> I understand, but as I said, there's no reliable way of doing that, so use-file-picker package is also not offering such functionality.

I'm closing it, feel free to open another issue if you have any questions
