### ISSUE TITLE
Failing to upload 1GB file

### ISSUE THREAD

**Issue by kmarler18** [Jaaneek/useFilePicker#96]
When I try to upload a 1GB mp4 file, the base64 string gets set to a blank string before being sent to my backend. This behavior doesn't occur with a 170MB file. I'm not allowed to share my exact code, but in general, this is what the call to the hook looks like...

```
  import { useImperativeFilePicker } from "use-file-picker";  

  const { openFilePicker, filesContent, loading } = useImperativeFilePicker({
    readAs: "DataURL",
    multiple: true,
  });
```

Let me know if it would be helpful to see anything else and I can do my best to share it. Any ideas what I might be doing wrong?

**Comment by MrKampla** [comment]
Hi @kmarler18, thanks for reporting this, but our hook does not cause this behavior. 

We're using the native [FileReader interface](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) for reading files selected by the user, which means the file size and the behavior is defined by the browser itself. There are no hard limits enforced by FileReader on file size, but the entire file that a user selects is loaded into memory, which means theoretically, the max size that can be handled depends on the user's machine. But each browser also has some mechanisms to detect if a website is taking unreasonable amounts of memory, and might kill the file uploading process in order not to freeze the system. These mechanisms are not documented anywhere, so I can't give you exact numbers, but I think uploading a single 1 GB file at once is a little too much. This file should be sliced into smaller chunks. If you can't enforce that on the user, then I don't have good news: use-file-picker does not support streaming at the moment, so you'd probably had to use the bare-bones FileReader API yourself and implement chunking.

Also, base64 encoding is quite inefficient when it comes to the data size. Reading as DataURL is intended to be used with small files that need to be read by the browser, e.g. displaying images on the website. May I ask why did you choose to read the file as DataURL instead of ArrayBuffer for example?

Here's an example function in TypeScript to load a big file in chunks:
```ts
type ChunkReadCallback = (chunkData: string | ArrayBuffer, chunkIndex: number) => void;
type ReadCompleteCallback = () => void;
type ErrorCallback = (error: ProgressEvent<FileReader>) => void;

interface ChunkReaderOptions {
    file: File;
    chunkSize: number;
    offset?: number;
    onChunkRead: ChunkReadCallback;
    onComplete: ReadCompleteCallback;
    onError?: ErrorCallback;
    readAs?: "DataURL" | "ArrayBuffer" | "Text" | "BinaryString";
}

function readFileInChunks(options: ChunkReaderOptions): void {
    const {
        file,
        chunkSize,
        offset = 0,
        onChunkRead,
        onComplete,
        onError,
        readAs = "DataURL",
    } = options;

    let currentOffset = offset;
    let chunkIndex = 0;

    function readNextChunk() {
        if (currentOffset >= file.size) {
            onComplete();
            return;
        }

        const chunk = file.slice(currentOffset, currentOffset + chunkSize);
        const reader = new FileReader();

        reader.onload = (e) => {
            if (e.target && e.target.result) {
                onChunkRead(e.target.result, chunkIndex);
                currentOffset += chunkSize;
                chunkIndex++;
                readNextChunk(); // Recursively read the next chunk
            }
        };

        reader.onerror = (e) => {
            if (onError) {
                onError(e);
            }
        };

        switch (readAs) {
            case "ArrayBuffer":
                reader.readAsArrayBuffer(chunk);
                break;
            case "Text":
                reader.readAsText(chunk);
                break;
            case "BinaryString":
                reader.readAsBinaryString(chunk);
                break;
            case "DataURL":
            default:
                reader.readAsDataURL(chunk);
                break;
        }
    }

    readNextChunk();
}
```

And it can be used as follows:

```ts
const fileInput = document.getElementById("fileInput") as HTMLInputElement;

fileInput.addEventListener("change", () => {
    const file = fileInput.files?.[0];
    if (!file) {
        console.error("No file selected");
        return;
    }

    readFileInChunks({
        file: file,
        chunkSize: 1024 * 1024, // 1MB chunks
        onChunkRead: (chunkData, chunkIndex) => {
            console.log(`Chunk ${chunkIndex}:`, chunkData);
            // Process the chunk data (e.g., upload to server)
        },
        onComplete: () => {
            console.log("All chunks have been read.");
        },
        onError: (error) => {
            console.error("Error reading file:", error);
        },
        readAs: "DataURL", // or "ArrayBuffer", "Text", etc.
    });
});

```

**Comment by kmarler18** [comment]
Thank you so much for the detailed answer @MrKampla! I'll experiment with this solution. I'm inheriting a file picker from another developer who chose to use base64. I'm not sure what his reasoning was.

**Comment by kmarler18** [comment]
Sorry, I’m a little confused… are you saying I can still utilize useImperativeFilePicker and pass it the multiple:true prop in conjunction with the other example function typescript code you provided?

**Comment by MrKampla** [comment]
Oh, I've misunderstood what you mean in the previous message. You wanted to ask if the chunking script I provided supports multiple file uploads, not the use file picker hook. 
The script just accepts a single file as a parameter, so if you write some glue code that maybe uses that `readFileInChunks` function in a loop, you should be able to get that working. In the example I provided, it only reads the first file from the selection, so no support for multiple files, but you should easily be able to change that. 

No, you can't use that script with useImperativeFilePicker, sorry if I was unclear about that. I meant that usefilepicker  supports multiple files being selected, but they all are loaded into the memory at once, so that's not what you're looking for.

**Comment by kmarler18** [comment]
No worries! Got it! You mentioned base64 seemed inefficient… what would you recommend?

**Comment by MrKampla** [comment]
Just use ArrayBuffer, this way it's going to be stored in raw binary format rather than encoded

**Comment by kmarler18** [comment]
Got it! And does your chunking script display a preview image after you've uploaded an image? My team likes that about useFilePicker so that would be nice to try to incorporate as well.

**Comment by Jaaneek** [comment]
@MrKampla explained everything very well


We might implement handling big files in the future but we are not planning it right now

If anyone is interested in implementing it feel free to open PR
